services:
  app:
    build: .
    container_name: cnd-scrapper
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./screenshots:/app/screenshots

